services:


  backend:

    build:
      context: ./backend


    container_name:
      nlp_backend


    ports:
      - "8000:8000"


    volumes:

      - ./backend/app:/app/app

      - ./data:/data


    depends_on:

      - redis



  frontend:

    build:
      context: ./frontend


    container_name:
      nlp_frontend


    ports:

      - "8501:8501"


    depends_on:

      - backend



  redis:


    image:
      redis:7-alpine


    container_name:
      nlp_redis


    ports:

      - "6379:6379"


    volumes:

      - redis_data:/data



volumes:

  redis_data:
